- name: install apache for debain
  apt: name=apache2 state=present
  when: ansible_os_family == "Debian"
  notify: restart apache2
- name: install apache for redhat
  yum: name={{redhat_apache}} state=present
  when: ansible_os_family == "RedHat"
  notify: restart httpd
